apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mcbprod
  name: watch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: mcbprod
      labels:
        app: watch
    spec:
      imagePullSecrets:
      - name: myregistrykey2
      containers:
        - name: watch
          image:  registry.synload.com/nucleo-watch:$BUILD_NUMBER
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx1g"
              #value: "kafka1.kafka.svc.cluster.local:9092"
            - name: MESH_NAME
              value: "mcbprod"
            - name: KAFKA_BROKER
              value: "192.168.88.146:9092,192.168.88.147:9092,192.168.88.145:9092"
